---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: k8s-repo-sync
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: k8s-repo-ssh-key
  url: ssh://git@github.com/DanielWinks/k8s
  ignore: |
    ./infra/purelb


# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: k8s-repo-sync
#   namespace: flux-system
# spec:
#   interval: 1m0s
#   path: ./infra
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: k8s-repo-sync
#   validation: client

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: system
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: k8s-repo-sync
  path: ./purelb/system
  prune: true
  validation: client

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: config
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: system
  sourceRef:
    kind: GitRepository
    name: k8s-repo-sync
  path: ./purelb/config
  prune: true
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: lbnodeagent
      namespace: purelb
